In [19]:
import numpy as np
from numpy.linalg import norm

In [40]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])
print(2 * b)

[-2  0 14]


In [23]:
norm(a, ord=1)

8.0

In [26]:
norm(a)

5.0990195135927845

In [33]:
norm(a - b, ord=1)

17.0

In [34]:
norm(a - b)

12.12435565298214

In [35]:
from scipy.spatial.distance import cdist

In [42]:
a = a.reshape(1, 3)
a.shape

(1, 3)

In [43]:
b = b.reshape(1, 3)
b.shape

(1, 3)

In [44]:
print('Manhaten dict = ', cdist(a, b, metric='cityblock'))

Manhaten dict =  [[22.]]


In [45]:
d = np.array([3, 0, 8, 9, -10])

In [47]:
d.shape

(5,)

In [48]:
d[np.newaxis, :].shape

(1, 5)

In [50]:
d.shape

(5,)

In [51]:
d[:, np.newaxis]

array([[  3],
       [  0],
       [  8],
       [  9],
       [-10]])

In [52]:
a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])

In [55]:
cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[14.2126704]])

In [56]:
len(a)

3

In [60]:
a.dot(b)

-41

In [61]:
a.dot(a)

70

In [62]:
norm(a)

8.366600265340756

In [66]:
import math
math.sqrt(70)

8.366600265340756

In [68]:
cos_angl = np.dot(a, b) / norm(a) /norm(b)
cos_angl

-0.6930264888773836

In [70]:
a = np.array([1, 2, 3])
b = np.array([-3, 1, 1])
a.dot(b)

2

In [75]:
a = np.array([True, False, True])
a

array([ True, False,  True])