In [1]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
v = np.arange(0, 20, 1)
v = v.reshape((4, 5))
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
v[2, 3]

13

In [24]:
v[2, :]

array([10, 11, 12, 13, 14])

In [25]:
v[:, 2]

array([ 2,  7, 12, 17])

In [27]:
v[[2, 3], [0, 0]]

array([10, 15])

In [28]:
v.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [39]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
b = np.random.randint(1, 35, (3, 3))
b

array([[21, 27, 11],
       [12, 21,  7],
       [15,  7, 29]])

In [49]:
c = a.dot(b)
c

array([[ 90,  90, 112],
       [234, 255, 253],
       [378, 420, 394]])

In [58]:
from numpy.linalg import det, matrix_rank

In [51]:
det(a)

6.66133814775094e-16

In [56]:
a.astype('float')

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [57]:
det(a)

6.66133814775094e-16

In [67]:
d = np.array([[1, 1, 2], [0, 1, 2]])
d

array([[1, 1, 2],
       [0, 1, 2]])

In [68]:
matrix_rank(d)

2

In [62]:
c.shape

(3, 3)

In [77]:
a = np.eye(4, 5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [79]:
s = a[[0, 3], [1, 3]]
s[0]

0.0